fix service script

diff --git a/templates/default/sysv.erb b/templates/default/sysv.erb
--- a/templates/default/sysv.erb
+++ b/templates/default/sysv.erb
@@ -22,6 +22,31 @@ SCRIPTNAME=/etc/init.d/$NAME
 
 ulimit <%= @ulimit %>
 
+RES_COL=60
+MOVE_TO_COL="echo -en \\033[${RES_COL}G"
+SETCOLOR_SUCCESS="echo -en \\033[1;32m"
+SETCOLOR_FAILURE="echo -en \\033[1;31m"
+SETCOLOR_WARNING="echo -en \\033[1;33m"
+SETCOLOR_NORMAL="echo -en \\033[0;39m"
+
+if [ -f /etc/init.d/functions ]; then
+. /etc/init.d/functions
+fi
+
+printStatus(){
+  $MOVE_TO_COL
+  echo -n "["
+  if test $1 == 0; then
+    $SETCOLOR_SUCCESS && echo -n $"  OK  "
+  else
+    $SETCOLOR_FAILURE && echo -n $"FAILED"
+  fi
+  $SETCOLOR_NORMAL
+  echo -n "]"
+  echo
+}
+
+
 case "$1" in
 start)
     printf "%-50s" "Starting $NAME..."
@@ -37,17 +62,30 @@ start)
         fi
 ;;
 status)
-        printf "%-50s" "Checking $NAME..."
-        if [ -f $PIDFILE ]; then
-            PID=`cat $PIDFILE`
-            if [ -z "`ps axf | grep ${PID} | grep -v grep`" ]; then
-                printf "%s\n" "Process dead but pidfile exists"
-            else
-                echo "Running"
-            fi
-        else
-            printf "%s\n" "Service not running"
-        fi
+if [ ! -z "$PIDFILE" ]; then
+  if [ -f "$PIDFILE" ]; then
+    if [ -s "$PIDFILE" ]; then
+      kill -0 `cat "$PIDFILE"` >/dev/null 2>&1
+      if [ $? -gt 0 ]; then
+        echo -n "Caddy pid file exist but no process with id $(cat $PIDFILE) is running" && printStatus 1
+        echo
+        exit 1
+      else
+        echo -n "Caddy is running with pid: $(cat $PIDFILE)" && printStatus 0
+        echo
+        exit 0
+      fi
+    else
+      echo -n "Caddy pid file exist but file is empty." && printStatus 1
+      echo
+      exit 4
+    fi
+  else
+    echo -n "Caddy is stopped, no PID file found." && printStatus 1
+    echo
+    exit 3
+  fi
+fi
 ;;
 stop)
         printf "%-50s" "Stopping $NAME"
